<!-- BEGIN ulist_open --><ul><!-- END ulist_open -->
<!-- BEGIN ulist_close --></ul><!-- END ulist_close -->

<!-- BEGIN olist_open --><ol type="{LIST_TYPE}"><!-- END olist_open -->
<!-- BEGIN olist_close --></ol><!-- END olist_close -->

<!-- BEGIN listitem --><li><!-- END listitem -->

<!-- BEGIN quote_open -->
<div style="width: 60%; background-color: #f6f6f6; font-family: Verdana; font-ize: 9px; color: #CC0000; padding: 10px; border-width:1px; border-color:#D5D5D5; border-style:solid;"><strong>QUOTE:</strong><br />
<!-- END quote_open -->
<!-- BEGIN quote_close -->
</div>
<!-- END quote_close -->

<!-- BEGIN code_open -->
<div style="width: 60%; background-color: #f6f6f6; font-family: Courier, Verdana; font-ize: 9px; color: #264779; padding: 10px; border-width:1px; border-color:#D5D5D5; border-style:solid;"><strong>CODE:</strong><br />
<!-- END code_open -->
<!-- BEGIN code_close -->
</div>
<!-- END code_close -->

<!-- BEGIN b_open --><strong><!-- END b_open -->
<!-- BEGIN b_close --></strong><!-- END b_close -->

<!-- BEGIN s_open --><span style="text-decoration:line-through"><!-- END s_open -->
<!-- BEGIN s_close --></span><!-- END s_close -->

<!-- BEGIN u_open --><span style="text-decoration: underline"><!-- END u_open -->
<!-- BEGIN u_close --></span><!-- END u_close -->

<!-- BEGIN i_open --><span style="font-style: italic"><!-- END i_open -->
<!-- BEGIN i_close --></span><!-- END i_close -->

<!-- BEGIN color_open --><span style="color: {COLOR}"><!-- END color_open -->
<!-- BEGIN color_close --></span><!-- END color_close -->

<!-- BEGIN font_open --><span style="font-family: {FONT}"><!-- END font_open -->
<!-- BEGIN font_close --></span><!-- END font_close -->

<!-- BEGIN size_open --><span style="font-size: {SIZE}px; line-height: normal"><!-- END size_open -->
<!-- BEGIN size_close --></span><!-- END size_close -->

<!-- BEGIN img --><img src="{URL}" alt="Image" class="bbcode_img" /><!-- END img -->

<!-- BEGIN url --><a href="{URL}">{DESCRIPTION}</a><!-- END url -->

<!-- BEGIN email --><a href="mailto:{EMAIL}">{EMAIL}</A><!-- END email -->
